name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        app: ['cli','desktop']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
          - app: cli
            projectPath: ./src/CandleMage.CLI/CandleMage.CLI.csproj
          - app: desktop
            projectPath: ./src/CandleMage.Desktop/CandleMage.Desktop.csproj
            
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
#    - name: Restore dependencies
#      run: dotnet restore ./src
#    - name: Build
#      run: dotnet restore ./src
    - name: Publish
      run: dotnet publish ${{ matrix.projectPath }} --runtime "${{ matrix.target }}" -c Release -o ./output
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.app }}-${{ matrix.target }}-${{ github.ref_name }}
        path: ./output